### ISSUE TITLE
Recommended number of CPUs required to run the pipeline too high

### ISSUE THREAD

**Issue by dmuiruri** [OSS-MLOPS-PLATFORM/oss-mlops-platform#21]
The installation script contains a variable `RECOMMENDED_CPUS=16`.
Although the script allows the installation to proceed with fewer CPU cores by answering 'yes' to the prompt, the recommended number is **considerably high**.

Establishing the minimum resources necessary to make local deploying and testing of the pipeline easier would be promising. Otherwise, other approaches, such as a lightweight pipeline version, can be explored.

**Comment by dmuiruri** [comment]
I tested the installation on a node with 14 cores and about 123GB of memory. The application of the configuration succeeded after about 14 re-tries, same results were observed on two occasions. This is related to issue #20 as a rough estimate of how long it may take takes on a given HW configuration. Should it be assumed that it would take longer for a node with fewer resources to complete the installation?

**Comment by K123AsJ0k1** [comment]
I think the amount of retries for the loop is roughly the same as long as there is 8 CPUs available for the current deployment, because otherwise kubernetes scheduler might make some pods stay in ContainerCreating, Pending or CrashLoopOff state due to the requested resources being roughly the following based on 'kubectl describe nodes' command:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                7975m (99%)        75800m (947%)
  memory             13708741120 (41%)  44390Mi (141%)
  ephemeral-storage  0 (0%)             0 (0%)
  hugepages-1Gi      0 (0%)             0 (0%)
  hugepages-2Mi      0 (0%)             0 (0%)
```

I also made a lighted deployment by modifying the following kustomize.yamls in the deployment:
- Kubeflow/manifests/in-cluster-setup/kustomization.yaml
- monitoring/kustomization.yaml

The modifications removed the following components:
- Katib
- Jupyter Web App
- Notebook Controller
- PVC Viewer
- Volumes Web App
- Tensorboards Controller
- Tensorboard Web App
- Training Operator
- Alert Manager

This lighter deployment was also modified to have the following updated versions:
- MLflow = 2.10.0, but its docker image needs to built and loaded into kind after setup
- Minio = RELEASE.2024-01-29T03-56-32Z
- PostgreSQL = 16
- Prometheus = v2.48.1
- Pushgateway = v1.6.2
- Grafana = 10.2.3

With this modifications the resource requirements changed to roughly:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                6745m (84%)        58800m (735%)
  memory             12000781568 (36%)  35686Mi (113%)
  ephemeral-storage  0 (0%)             0 (0%)
  hugepages-1Gi      0 (0%)             0 (0%)
  hugepages-2Mi      0 (0%)             0 (0%)
```

If we compare these to my customized GitLab OSS with KubeRay (2 CPU requirement), self-made components and 1 inference service (1 CPU requirement), the resource requirement is:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                6885m (86%)        11100m (138%)
  memory             13044138752 (78%)  13378805248 (80%)
  ephemeral-storage  0 (0%)             0 (0%)
  hugepages-1Gi      0 (0%)             0 (0%)
  hugepages-2Mi      0 (0%)             0 (0%)  
```
This means the CPU requirement of a OSS with standalone kubeflow pipeline is roughly around 4 CPU, which means the multi-user kubeflow increases it to around 7 CPU and to 8 CPU with the optional features. If we want to decrease the resource requirements, while ensuring that the critical components like kubeflow, Mflow, MinIO, Postgre, mySQL, Istio, Kserve, Prometheus and Grafana are available for the user, a potential way would be the following: 

- If possible, decrease the CPU requests of component, while ensuring that performance degradation doesn't impact user too much 
- If possible, set memory request and limit to be the same, while ensuring that performance degradation doesn't impact user too much
- Set PriorityClasses for critical components

This approach will however require some testing to show viability.

**Comment by JoaquinRivesGambin** [comment]
@K123AsJ0k1 Yup, I think we can make those components non-essential components as optional.

Ray is already optional and set to false by default, so that good.

Then, we can also update the InferenceServiceSpec in the demos to lower the resources.

I think that should be enough for now so that it can be run in 8 CPUs without issues, and it shouldn't take a lot of effort to implement.

**Comment by JoaquinRivesGambin** [comment]
The other option is to have standalone KFP and standalone Kserve, but as I said earlier, I would try to avoid that, as they behave differently, and the way to interact with it changes. So we would need to create alternative instructions for every tutorial/use-case. It could get quite messy and difficult to maintain, test, etc.

**Comment by JoaquinRivesGambin** [comment]
> I tested the installation on a node with 14 cores and about 123GB of memory. The application of the configuration succeeded after about 14 re-tries, same results were observed on two occasions. This is related to issue #20 as a rough estimate of how long it may take takes on a given HW configuration. Should it be assumed that it would take longer for a node with fewer resources to complete the installation?

Usually yes, depending of how fast the machine everything will get up and running sooner. However, it sometimes depends a lot on the internet speed as well,  as pulling all the many docker images can take a while if it is slow.

Applying all the manifest at one as we do now will always take a few re-tries, it is unavoidable, unless we deploy in steps, waiting for the necessary resources to become ready after every step. But yes, I think the installation would be more clear and easier to debug if we avoid that infinite loop and go for the deployment in steps. I created an new issue for it:
[https://github.com/OSS-MLOPS-PLATFORM/oss-mlops-platform/issues/22](https://github.com/OSS-MLOPS-PLATFORM/oss-mlops-platform/issues/22)

**Comment by K123AsJ0k1** [comment]
In order to get access to the kubeflow pipeline dashboard in CPouta VM, I used the following commands:
```
ssh -L 8080:localhost:8080 pouta
kubectl port-forward svc/ml-pipeline-ui -n kubeflow 8080:80
```
By using http://localhost:8080 as client url, I managed to run pull data and preprocess components of the Git Lab OSS wine quality demo pipeline with train getting  CreateContainerConfigError due to aws-secret not being found. I will try to fix this by adding the aws-secret.yaml into the in-cluster-setup and modifying the kustomization.yaml to use that as a resource.

**Comment by K123AsJ0k1** [comment]
Train component now runs, but when it tries to log the model to MLflow it gets the following error: 
```
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/preview/mlflow/registered-models/create failed with error code 404 != 200. Response body: '<!doctype html>
```
I will recheck and modify the used demo pipeline to fix this.

**Comment by JoaquinRivesGambin** [comment]
@K123AsJ0k1 Okay, that's awsome. Have you tried tried Kserve with the single-user kubeflow pipelines version? Does it changes too much the way to interact with it?

About the mlflow error, I remember you mention you updated the mlflow version? I have gotten that type of error in the past after changing mlflow versions. It could be that the API in new version has changed.

**Comment by K123AsJ0k1** [comment]
@JoaquinRivesGambin I fixed the mlflow issue by chancing the old package version to 2.4.1 in train and evaluate, which made train and evaluate go green. I also have managed to make deploy model step deploy a inference service by doing the following files modifications in deployment/kubeflow-custom:

```
kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aws-secret.yaml # modification
- kserve-inference-namespace.yaml # addition
- kserve-deployer.yaml # addition
- kserve-sa.yaml # modification
```

```
aws-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kubeflow # changed to enable kubeflow components in kubeflow namespace to use this secret
type: Opaque
data:
  # your BASE64 encoded AWS_ACCESS_KEY_ID
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  # your BASE64 encoded AWS_SECRET_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
```

```
kserve-inference.namespace.yaml 
# Required to establish a kserve-inference namespaces for deploy model and inference

apiVersion: v1
kind: Namespace
metadata:
  name: kserve-inference
```

```
kserve-deployer.yaml 
# Required for deploy model to have the necessery permissions to create inference services

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-deployer
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - persistentvolumes
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - workflows
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
  - verbs:
      - '*'
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
  - verbs:
      - '*'
    apiGroups:
      - kubeflow.org
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - machinelearning.seldon.io
    resources:
      - seldondeployments
  - verbs:
      - '*'
    apiGroups:
      - serving.kserve.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - networking.istio.io
    resources:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-runner-binding-cluster
  labels:
    application-crd-id: kubeflow-pipelines
subjects:
  - kind: ServiceAccount
    name: pipeline-runner
    namespace: kubeflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-deployer
```

```
kserve-sa.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: kserve-inference # Changed to enable use in the inference service namespace
  annotations:
     serving.kserve.io/s3-endpoint: mlflow-minio-service.mlflow.svc.cluster.local:9000
     serving.kserve.io/s3-usehttps: "0"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  AWS_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
  namespace: kserve-inference # Changed to enable use in the inference service namespace
secrets:
- name: mysecret

```

By using the commands

```
kubectl get isvc -n kserve-inference
kubectl get pods -n kserve-inference
kubectl get service -n kserve-inference
```

we get the following print:

```
$ kubectl get isvc -n kserve-inference
NAME           URL                                                READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION            AGE
wine-quality   http://wine-quality.kserve-inference.example.com   True           100                              wine-quality-predictor-00001   16m
$ kubectl get pods -n kserve-inference
NAME                                                       READY   STATUS    RESTARTS   AGE
wine-quality-predictor-00001-deployment-6dc4546b8c-hbqwg   2/2     Running   0          16m
$ kubectl get service -n kserve-inference
NAME                                   TYPE           CLUSTER-IP     EXTERNAL-IP                                            PORT(S)                                              AGE
wine-quality                           ExternalName   <none>         knative-local-gateway.istio-system.svc.cluster.local   <none>                                               14m
wine-quality-predictor                 ExternalName   <none>         knative-local-gateway.istio-system.svc.cluster.local   80/TCP                                               14m
wine-quality-predictor-00001           ClusterIP      10.96.19.70    <none>                                                 80/TCP,443/TCP                                       16m
wine-quality-predictor-00001-private   ClusterIP      10.96.165.43   <none>                                                 80/TCP,443/TCP,9090/TCP,9091/TCP,8022/TCP,8012/TCP   16m

```
Currently I am having some problem with the inference set getting the following error:

```
NAME          READY      PREV    LATEST  URL
wine-quality  True          0       100  
http://wine-quality.kserve-inference.example.com/
[KFP Executor 2024-02-07 09:11:29,642 INFO]: 
Inference service status:
{'address': {'url': '
http://wine-quality.kserve-inference.svc.cluster.local/
'}, 'components': {'predictor': {'address': {'url': 'http://wine-quality-predictor.kserve-inference.svc.cluster.local'}, 'latest
http://wine-quality-predictor.kserve-inference.svc.cluster.local/
'}, 'latestCreatedRevision': 'wine-quality-predictor-00001', 'latestReadyRevision': 'wine-quality-predictor-00001', 'latestRolledoutRevision': 'wine-quality-predictor-00001', 'traffic': [{'latestRevision': True, 'percent': 100, 'revisionName': 'wine-quality-predictor-00001'}], 'url': 'http://wine-quality-predictor.kserve-inference.example.com'}}, 'conditions': [{'lastTransitionTime': '2024-02-07T09:11:26Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '
http://wine-quality-predictor.kserve-inference.example.com/
'}}, 'conditions': [{'lastTransitionTime': '2024-02-07T09:11:26Z', 'status': 'True', 'type': 'IngressReady'}, {'lastTransitionTime': '2024-02-07T09:11:25Z', 'severity': 'Info', 'status': 'True', 'type': 'LatestDeploymentReady'}, {'lastTransitionTime': '2024-02-07T09:11:25Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorConfigurationReady'}, {'lastTransitionTime': '2024-02-07T09:11:26Z', 'status': 'True', 'type': 'PredictorReady'}, {'lastTransitionTime': '2024-02-07T09:11:26Z', 'severity': 'Info', 'status': 'True', 'type': 'PredictorRouteReady'}, {'lastTransitionTime': '2024-02-07T09:11:26Z', 'status': 'True', 'type': 'Ready'}, {'lastTransitionTime': '2024-02-07T09:11:26Z', 'severity': 'Info', 'status': 'True', 'type': 'RoutesReady'}], 'modelStatus': {'copies': {'failedCopies': 0, 'totalCopies': 1}, 'states': {'activeModelState': 'Loaded', 'targetModelState': 'Loaded'}, 'transitionStatus': 'UpToDate'}, 'observedGeneration': 1, 'url': 'http://wine-quality.kserve-inference.example.com'}
http://wine-quality.kserve-inference.example.com/
'}
[KFP Executor 2024-02-07 09:11:29,642 INFO]: 
Inference service URL:
http://wine-quality.kserve-inference.svc.cluster.local/
[KFP Executor 2024-02-07 09:11:29,707 INFO]: 
Prediction response:
{"detail":"Method Not Allowed"}
```
I will modify the inference step for the API changes that have happened for kserve.
