### ISSUE TITLE
OSS Local and Remote Dashboard URL Access

### ISSUE THREAD

**Issue by K123AsJ0k1** [OSS-MLOPS-PLATFORM/oss-mlops-platform#26]
In the GitLab OSS, a user could minimize the required actions for manual dashboard port forwarding to only writing the associated URL in the browser by using one of the following Ngnix ingress options for a service:

- Ingress for dashboard with no login:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: (given_name)-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
spec:
  rules:
  - host: (given_name)-ui.(local/remote)
    http:
      paths:
        - backend:
            service:
              name: (service_name)
              port:
                number: (service_port)
          path: /
          pathType: Prefix

```

- Ingress for dashboards with login:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: (given_name)-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.il/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: (given_name).(local/remote)
    http:
      paths:
        - backend:
            service:
              name: (service_name)
              port:
                number: (service_port)
          path: /
          pathType: Prefix
```

When the ingresses were setup, the user could then just configure /etc/hosts using

```
sudo cat /etc/hosts
sudo nano /etc/hosts
```

into following:

```
127.0.0.1	   dashboard-ui.local
127.0.0.1          dashboard.local
VM IP              dashboard-ui.remote
VM IP              dashboard.remote
``` 

In the case of CPouta VMs, the user would also need to open a port using the following security rule:

- Rule = Custom TCP rule
- Description = Dashboard ingresses
- Open Port = Port
- Port = 80
- Remote = CIDR
- CIDR = users local computer IP

The user can then just write URLs http://dashboard-ui.local or http://dashboard-ui.remote to easily get access to the dashboards of both local and remote OSS. Since Ngnix has been replaced by Istio, I wonder what are the necessary steps to use Istio to enable URL access to all OSS dashboards both locally and remotely?

**Comment by K123AsJ0k1** [comment]
In order to make Istio debugging easier, I tested out if [Kiali](https://istio.io/latest/docs/ops/integrations/kiali/#installation) could be installed into OSS. After a bit of trial and error, I managed to do it with the following actions:

1. Download the kiali.yaml provided by Istio
2. Separate the kiali.yaml into parts to use kustomize (optional)
3. Modify kiali-configmap.yaml external services have the following:
```
prometheus:
  url: "http://prometheus-service.monitoring:8080/"
grafana:
  enabled: true
  in_cluster_url: 'http://grafana.monitoring:3000/'
```
4. Get the current istiod.yaml with
```
kubectl get deployment istiod -n istio-system -o yaml > istiod.yaml
```
5. Change istiod.yaml enviromental variable ENABLE_DEBUG_ON_HTTP from 'false' to 'true'
6. Apply the yamls or kustomize with:

```
kubectl apply -f istiod.yaml
kubectl apply -f kiali.yaml
kubectl apply -k istio-kiali deployment # Optional
```
7. Check that kiali is running with:
```
kubectl get pods -n istio-system
```
8. Get Kiali dashboard with:
```
ssh -L 20001:localhost:20001 (vm) # If remote
kubectl port-forward svc/kiali -n istio-system 20001:20001
```
9. Open http://localhost:20001

The Kiali dashboard enables monitoring the traffic experienced by the gateways and virtual  services, which we can see by opening the central kubeflow dasbhoard using:

```
ssh -L 8080:localhost:8080 (Vm) # Remote
kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80
```

Kiali also enables modification of Istio configuration like gateways and virtual services through the dashboard, which makes service creation and testing faster. I am currently trying to find a way to get URL access to CPouta OSS Prometheus by creating a gateway, virtual service and a suitable security rules.
